[package]
name = "spot"
version = "0.1.0"
edition = "2018"

[dependencies.gtk]
version = "^0.9.0"
features = ["v3_24"]

[dependencies.gdk]
version = "^0.13.0"
features = ["v3_24"]

[dependencies.gio]
version = "^0.9.0"
features = ["v2_60"]

[dependencies.glib]
version = "^0.10.0"
features = ["v2_60"]

[dependencies.librespot]
version = "0.1.3"
features = ["pulseaudio-backend"]

[dependencies.protobuf]
version = "2.8.1"

[dependencies.tokio-core]
version = "^0.1.18"

[dependencies.futures01]
version = "0.1.29"

[dependencies.futures]
package = "futures"
version = "0.3.5"
features = ["compat"]

[dependencies.serde]
version = "^1.0.118"
features = ["derive"]

[dependencies.serde_json]
version = "^1.0.60"

[dependencies.isahc]
version = "^0.9.14"
features = ["json"]

[dependencies]
secret-service = "^1.1.3"
gdk-pixbuf = "^0.9.0"
gtk-test = "^0.6.0"
gladis = "^0.4.0"
ref_filter_map = "^1.0.1"
regex = "^1.4.2"
