[package]
name = "spot"
version = "0.1.9"
edition = "2018"
license = "MIT"

[features]
warn-cache = []

[dependencies.gtk]
version = "^0.9.0"
features = ["v3_24"]

[dependencies.gdk]
version = "^0.13.0"
features = ["v3_24"]

[dependencies.gio]
version = "^0.9.0"
features = ["v2_60"]

[dependencies.glib]
version = "^0.10.0"
features = ["v2_60"]

[dependencies.librespot]
version = "0.1.6"
features = ["alsa-backend", "pulseaudio-backend"]

[dependencies.protobuf]
version = "2.8.1"

[dependencies.tokio-core]
version = "^0.1.18"

[dependencies.futures01]
version = "0.1.30"

[dependencies.futures]
package = "futures"
version = "0.3.13"
features = ["compat"]

[dependencies.serde]
version = "^1.0.123"
features = ["derive"]

[dependencies.serde_json]
version = "^1.0.64"

[dependencies.isahc]
version = "^1.1.0"
features = ["json"]

[dependencies.rand]
version = "^0.8.3"
features = ["small_rng"] 

[dependencies]
secret-service = "^2.0.1"
gdk-pixbuf = "^0.9.0"
libhandy = "^0.7.1"
gladis = "^0.4.0"
ref_filter_map = "^1.0.1"
regex = "^1.4.3"
async-std = "^1.9.0"
form_urlencoded = "^1.0.1"
zbus = "^2.0.0-beta.2"
zvariant = "^2.5.0"
zvariant_derive = "^2.5.0"
thiserror = "^1.0.24"
lazy_static = "^1.4.0"