name: spot-main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true
        components: rustfmt

    - name: Install system dependencies
      run: |
        sudo apt update -q
        sudo apt install -y build-essential appstream-util pkg-config meson libssl-dev libglib2.0-dev-bin libgtk-3-dev libasound2-dev libpulse-dev

    - name: Install libhandy
      run: |
        wget -O libhandy-1-dev.deb http://mirrors.kernel.org/ubuntu/pool/universe/libh/libhandy-1/libhandy-1-dev_1.0.0-2_amd64.deb
        wget -O gir1.2-handy-1.deb http://mirrors.kernel.org/ubuntu/pool/main/libh/libhandy-1/gir1.2-handy-1_1.0.0-2_amd64.deb
        wget -O libhandy-1.deb http://mirrors.kernel.org/ubuntu/pool/main/libh/libhandy-1/libhandy-1-0_1.0.0-2_amd64.deb
        sudo apt install -y ./libhandy-1.deb
        sudo apt install -y ./gir1.2-handy-1.deb
        sudo apt install -y ./libhandy-1-dev.deb

    - name: Build
      run: meson target -Dbuildtype=debug -Doffline=false && ninja -C target

    - name: Test
      run: meson test -C target --verbose